source 'https://rubygems.org'

gem 'rails'
gem 'pg'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem "devise"
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'owlcarousel2-rails', github: 'openscript/owlcarousel2-rails'

group :development do
  gem 'byebug'
  gem 'web-console'
  gem 'spring'
  gem 'quiet_assets'
end

group :test, :development do
  gem 'rspec-rails'
  gem 'launchy'
  gem 'pry'
  gem 'capybara'
  gem 'factory_girl_rails'
end

group :test do
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
end
